# Generated by Django 5.2.6 on 2025-09-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("total_questions", models.IntegerField(default=0)),
                ("correct", models.IntegerField(default=0)),
                ("wrong", models.IntegerField(default=0)),
                ("score", models.FloatField(blank=True, null=True)),
                ("details", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "qtype",
                    models.CharField(
                        choices=[
                            ("mcq", "Multiple Choice"),
                            ("fib", "Fill in the blank"),
                        ],
                        default="mcq",
                        max_length=10,
                    ),
                ),
                ("difficulty", models.IntegerField(default=1)),
                ("choices", models.JSONField(blank=True, null=True)),
                ("correct_answer", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("order", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
